### PR TITLE
Update open.lua

### PR DESCRIPTION
**Pull request by AyrianaWoW**
Updated for extended detailed output when opening mails, specifically Auction House mails with/without money

### CODE REVIEW

**Comment by AyrianaWoW** [comment]
If this commit is approved, then there is a viable updated feature-rich alternative to the baseline 'Postal' and even the 'Mail' addon that lack several of the features of Postal-Returned.

**Comment by veechs** [comment]
Thanks, I’ll take a look at merging this as soon as I have a chance.

**Comment by veechs** [comment]
Added in https://github.com/veechs/Postal-Returned/commit/17e946f899b4f063acc5725f81da0024338e26a5.

I didn't merge the pull request because I wanted to tweak the things outlined in the linked commit, but thank you for bringing these improvements to my attention!

**Comment by AyrianaWoW** [comment]
Yes I always appreciate updates and thank you for doing so!
I'm a LUA newbie so I do my best to poke the original author so they can improve/fix it better than I could :)

**Pull request closed without merging**
